#!/bin/bash
# Install NetworkManager dispatcher for persistent routing

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$SCRIPT_DIR/lib/common.sh"

check_root

print_header "Installing NetworkManager Dispatcher"

DISPATCHER_DIR="/etc/NetworkManager/dispatcher.d"
DISPATCHER_SCRIPT="$DISPATCHER_DIR/99-modem-routing"
DISPATCHER_CONTENT="$SCRIPT_DIR/lib/nm-dispatcher-routing.sh"

# Create dispatcher directory if needed
if [ ! -d "$DISPATCHER_DIR" ]; then
    log_info "Creating dispatcher directory: $DISPATCHER_DIR"
    mkdir -p "$DISPATCHER_DIR"
fi

# Create dispatcher script content
print_step "Creating dispatcher script..."
cat > "$DISPATCHER_CONTENT" << 'EOF'
#!/bin/bash
# NetworkManager dispatcher script to maintain multipath routing
# Auto-generated by ProxyFarm

INTERFACE=$1
ACTION=$2

# Log to syslog
logger "ProxyFarm NM-Dispatcher: $INTERFACE $ACTION - Checking modem routing"

# Only run on connection up/down events
if [[ "$ACTION" != "up" && "$ACTION" != "down" && "$ACTION" != "connectivity-change" ]]; then
    exit 0
fi

# Wait for interfaces to stabilize
sleep 2

# Run the routing setup script
ROUTING_SCRIPT="/root/repo/proxyfarm/scripts/setup/routing.sh"
if [ -f "$ROUTING_SCRIPT" ]; then
    $ROUTING_SCRIPT >> /var/log/proxyfarm_routing.log 2>&1
    logger "ProxyFarm NM-Dispatcher: Routing setup completed"
else
    logger "ProxyFarm NM-Dispatcher: ERROR - Routing script not found: $ROUTING_SCRIPT"
fi
EOF

chmod +x "$DISPATCHER_CONTENT"

# Install dispatcher
print_step "Installing dispatcher to $DISPATCHER_SCRIPT..."
backup_file "$DISPATCHER_SCRIPT" "nm-dispatcher-routing"
cp "$DISPATCHER_CONTENT" "$DISPATCHER_SCRIPT"
chmod +x "$DISPATCHER_SCRIPT"

log_success "NetworkManager Dispatcher installed successfully"
echo ""
echo "The dispatcher will automatically run whenever NetworkManager"
echo "brings up or changes network connections."
echo ""
echo "Logs:"
echo "  - journalctl -f | grep 'ProxyFarm NM-Dispatcher'"
echo "  - tail -f /var/log/proxyfarm_routing.log"
echo ""
